name: Charlesbclark
favicon: null
layout_spectrum: 0.23315
typography_spectrum: 0.5770872381981462
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#010101'
    - '#d5ced5'
    - '#e39301'
    - '#816d76'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
