name: Charlesbclark
favicon: null
layout_spectrum: 0.5545180167537183
typography_spectrum: 0.5770872381981462
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.9938936089165509
  lightness: 0.3525374785531312
  saturation: 0.9445933641400188
  rhythmicContrast: 0.41006268048658967
purpose: []
